server:
  port: 8080


spring:
  # config database
  datasource:
    url: jdbc:mysql://localhost:3306/agenda_contactos?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  #config hibernate
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update